### PR TITLE
Support res.set/setHeader with a map of headers

### PR DESCRIPTION
**Pull request by quantumew**
https://expressjs.com/en/api.html#res.set

@Aminadav Let me know when you can get this in!! Thanks!!

### CODE REVIEW

**Comment by quantumew** [comment]
@Aminadav Awesome, thanks for the speedy response. Let me know if it will be a bit before it gets published. Might internally publish my fork to get people by. A lot of devs use this as part of our preview tool. Great tool!

**Comment by quantumew** [comment]
Perfect!

**Comment by quantumew** [comment]
Sorry to bother, I noticed a new version of run-middleware was released but
when I diff'd the changes it looks like they are the same. Just checking in
case you intended to release my changes with that release. Thanks again
man!!

**Comment by Aminadav** [comment]
Wow, mistake. Now I published again. Please see the version now:
https://unpkg.com/run-middleware@0.9.10/index.js

**Comment by quantumew** [comment]
It happens! Thanks so much!

**Pull request merged**
